### PR TITLE
Document at package level

### PR DESCRIPTION
**Pull request by bobturneruk**
The plan is to make some package level documentation for most, if not all, of the main `GPy` packages.

### CODE REVIEW

**Comment by bobturneruk** [comment]
A test readthedocs build is here:

https://rse-sheffield-gpy.readthedocs.io/en/package-level-info/

**Comment by bobturneruk** [comment]
Will resolve #820.

**Comment by bobturneruk** [comment]
My intention here is to achieve the following:

- [x] Clarify "homepage" (https://rse-sheffield-gpy.readthedocs.io/en/docs/)

- [x] Include a general description of "architecture" on the "homepage" (https://rse-sheffield-gpy.readthedocs.io/en/package-level-info/)

Ensure each of the following have an introduction (https://rse-sheffield-gpy.readthedocs.io/en/package-level-info/)

- [x] GPy.core package
- [x] GPy.core.parameterization package
- [x] GPy.models package
- [x] GPy.kern package
- [x] GPy.likelihoods package (reviewed)
- [ ] GPy.mappings package
- [x] GPy.examples package
- [x] GPy.util package
- [x] GPy.plotting package
- [ ] GPy.inference.optimization package
- [x] GPy.inference.latent_function_inference package
- [ ] GPy.inference.mcmc package

**Review by lawrennd — APPROVED** [review]
Documentation changes look good.

**Comment by bobturneruk** [comment]
Given the approval, I'm going to move this from "draft" to "ready".

**Comment by bobturneruk** [comment]
I think I will need to rebase to pass CI. I'll work on this.

**Comment by bobturneruk** [comment]
I've made some minor changes - looks like the CI is now passing. @lawrennd this is, I think, ready to merge, but I can't merge it myself.

**Comment by bobturneruk** [comment]
CI is no longer passing. I will look into this again.

**Comment by jbect** [comment]
> CI is no longer passing. I will look into this again.

Hi @bobturneruk,
PR #842 solves some of the CI failures that you see (the ones occuring in Python 3.5).

**Comment by bobturneruk** [comment]
Thanks @jbect - hopefully @lawrennd will get a chance to look at PR #842 soon.

**Comment by bobturneruk** [comment]
Other failures I suspect are execution environment related somehow.

**Comment by lawrennd** [comment]
Merged #842

**Comment by jbect** [comment]
@bobturneruk you also have issue #844 in your CI failures.

**Comment by bobturneruk** [comment]
Thanks @jbect - I'll rebase once https://github.com/SheffieldML/GPy/pull/845 is merged.

**Comment by jbect** [comment]
Ok, all green in #845, you just have to wait for the merge :wink:.

**Comment by bobturneruk** [comment]
Great, thanks! I think we are reliant on @lawrennd for this.

**Comment by lawrennd** [comment]
Done!

**Pull request merged**
