### PR TITLE
added extended version of MLP function

### PR DESCRIPTION
**Pull request by msbauer**
This is an extended version of the MLP mean function which supports multiple layers and several activation functions

### CODE REVIEW

**Comment by zhenwendai** [comment]
It seems the unit-test fails because gradient check does not pass. Could you have a look into it?

**Comment by msbauer** [comment]
The unittests for the new code run fine on my local machine with python 2.7. Rerunning the tests on the server, they now pass partly. I'm not sure where this problem comes from. Do you have any suggestions how to diagnose what might be going wrong?

**Comment by zhenwendai** [comment]
Matthias, could you fix the randomness in the test case and update the pull request? Thanks!

**Comment by msbauer** [comment]
Zhenwen, sorry for the long wait. I have fixed the seed and the checks now run except for the codecov/changes where I don't understand the coverage changes

**Comment by zhenwendai** [comment]
Cool! Thanks, Matthias!

**Pull request merged**
