### PR TITLE
Fix import of cythonized modules

### PR DESCRIPTION
**Pull request by skycaptain**
With the latest GPy from pip, I'm getting these warnings:

```
warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy
```

Even though the cython modules are compiled and installed next to the python sources, python fails to import them. Also importing them directly gives me an ImportError:

```python
>>> from GPy.util import choleskies_cython
ImportError: cannot import name 'choleskies_cython' from 'GPy.util' (/usr/local/lib/python3.7/site-packages/GPy/util/__init__.py)
```

After playing around with the setup.py, the only solution I found, was moving the GPy source code into a src directory, and changing the paths in setup.py accordingly. I know this is a rather dramatic change; also this PR might not be complete yet, as I might have overlooked some paths.

This is somewhat related to cython build errors of others: #684, #686, #691, #690, #677. 

Finally, this PR also includes the changes from #691, #690, #677 to make things work, and updates the cython c sources.

#### System

Python: 3.7.0.final.0 via Homebrew
OS: OSx 10.13.6
pip: 18.1
setuptools: 40.2.0
Cython: 0.29.0
numpy: 1.15.2
matplotlib: 2.2.3

### CODE REVIEW

**Comment by darthdeus** [comment]
Is there any solution to this while the PR is waiting to be merged? I'm getting the same warning.

**Comment by jakubigla** [comment]
I'm still getting these while having the latest libraries
```
Cython                 0.29.16 
GPy                    1.9.9              
GPyOpt                 1.2.6  
numpy                  1.18.2 
....
```

**Comment by andreufont** [comment]
I'm also getting the same warnings / errors when using GPy 1.10.0

**Comment by astro-YYH** [comment]
I got these warnings while using GPy 1.10.0, cython 0.29.35

**Pull request closed without merging**
