### PR TITLE
FIX: state_space_cython misc

### PR DESCRIPTION
**Pull request by ajgpitch**
add missing colons and fix indentation

### CODE REVIEW

**Comment by ajgpitch** [comment]
This fixes #696

**Comment by zhenwendai** [comment]
I have fixed the failed test case regarding the new version of matplotlib. @ajgpitch Could you update the branch? It seems that your changes fail on Python 2.7. Could you have a look at it? Thanks.

**Comment by ajgpitch** [comment]
I have merged in the latest `devel` branch and fixed another typo. 
Tests for this may not pass until #693 and #695 are merged.

**Comment by ajgpitch** [comment]
This error in py2 illustrates why #695 is needed and #720 is advisable. The fix was made in `state_space_cython.pyx` but this had to be manually cythonized. I have done this now and will try another push

**Comment by ajgpitch** [comment]
I also notice that there are no Travis tests for Python 3.7

**Comment by jbect** [comment]
This PR should be closed, since it has been merged as part of PR #719.

**Comment by ekalosak** [comment]
Closing due to https://github.com/SheffieldML/GPy/pull/697#issuecomment-626277808
Thank you @jbect and @ajgpitch .

**Pull request closed without merging**
