### PR TITLE
Added pep.py -- Sparse Gaussian processes using Power Expectation Propagation

### PR DESCRIPTION
**Pull request by thangbui**
This approach allows interpolation between FITC (EP or alpha = 1), and Titsias's variational (VarDTC, VFE when alpha = 0).

Reference: A Unifying Framework for Sparse Gaussian Process Approximation using Power Expectation Propagation https://arxiv.org/abs/1605.07066

### CODE REVIEW

**Comment by lawrennd** [comment]
Wow! That's super cool Thang!

@mzwiessle, @zhenwendai it would be great to get this incorporated as soon
as feasilble. @zhenwendai do you have time to take a look?

Neil

**Comment by thangbui** [comment]
Hi All,

I also provide a script comparing different techniques here https://github.com/thangbui/sparseGP_powerEP/blob/master/python/sgp/tests/test_PEP_GPy.py

Thanks,
Thang.

**Comment by mzwiessele** [comment]
Great stuff! Could you add the test script as a test in GPy so the code is being tested within the GPy tests?

**Comment by thangbui** [comment]
@mzwiessele I added a test script which checks grads (as in fitc) and makes sure special cases of PEP are FITC and VarDTC -- not sure if this is enough.

**Comment by zhenwendai** [comment]
Great work! Thanks a lot, @thangbui! The test case of PEPgradienttest sometime fails randomly because of the random generated dataset. Could you fix the seed? 

The codecov does not get updated with the recent commit. I don't know why.

**Comment by zhenwendai** [comment]
@mzwiessele, could you have a look at why the added test case is added but the coverage does not increase? I am not familiar with codecov.

**Comment by mzwiessele** [comment]
Sure as soon as I have recovered, Ill give it a thorogh look.

**Comment by mzwiessele** [comment]
It is simple: Tests for nosetests need to have "test" in their name. pep.py is not being run as a test....

**Comment by thangbui** [comment]
Thanks @mzwiessele and @zhenwendai for the merge!

**Comment by mzwiessele** [comment]
Thanks for the contribution! Looking forward to the next module : )

**Pull request merged**
