### PR TITLE
Fix DSYR function (See https://github.com/scipy/scipy/issues/8155)

### PR DESCRIPTION
**Pull request by pgmoren**
DSYR function (rank-one update) was discarding the output.

NOTE: As a consequence of fixing this, the unit test "test_EP_with_StudentT". I am skipping the test temporally.

### CODE REVIEW

**Comment by alansaul** [comment]
Good catch. Given the reply to the issue scipy/scipy#8155 we should make sure that we don't have any other odd behaviour due to mis-specified flags. The only other "overwrite" flag I can see in GPy is in the function 'tdot_blas'.

**Comment by pgmoren** [comment]
I seems that the pull request fails because in scipy from 1.0.0 there is no longer sp.linalg.solve_lyapunov. The equivalent one is sp.linalg.solve_continuous_lyapunov. Should I open a new pull request for this one or should I amend this? Should I guarantee backward compatibility or do I use directly sp.linalg.solve_continuous_lyapunov? Thanks.

**Comment by alansaul** [comment]
This was a scipy bug, they meant to leave an alias for backwards compatibility, see: scipy/scipy#8082 . It looks like this change will be reverted in 1.1.0 but that doesn't help us much in the short term, and we still have the issue that users of 1.0.0 will have errors.

Our current scipy dependency is 0.12 so I would say try and maintain backwards compatibility as a jump up to 1.0.0 is perhaps a bit much, many will still be using versions such as 0.17.

I think its easiest to just amend this pull request with a backwards compatibility work around

```
try:
    from scipy.linalg import solve_continuous_lyapunov as lyap
except ImportError:
    from scipy.linalg import solve_lyapunov as lyap
```

What do you think?

**Comment by zhenwendai** [comment]
This looks good. Alan, can you quickly fix it? For us, it will take much longer.

**Comment by pgmoren** [comment]
Yes, that would be helpful. But otherwise let me know and I will amend it. It will take few days longer though. Btw, I checked and tdot_blas is working as expected.

**Comment by alansaul** [comment]
I can do that no problem yes. The neatest way (updating this existing pull request) is for me to edit your fork and make changes:

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

However since you have protocols as to what can be changed without having it checked again, which I assume includes others pushing code to your fork, the alternative and perhaps simpler is for me to copy your PR and make another PR with the suggested changes above. Are you happy with this?

**Comment by pgmoren** [comment]
Both options are ok to me. I added you as a collaborator in my fork so I guess you can now push your changes to it (as long as the code you push to it is a new commit should be ok). Otherwise, feel free to create a new pull request and replicate the changes. In any case, thanks!

**Comment by alansaul** [comment]
Looking at it again Pablo I've just realised you were correctly suggesting that the code changes you made were independent of the reason the build failed, hence suggesting making a new PR. The error occurs here:

```
GPy/kern/src/sde_stationary.py", line 72, in sde
    Pinf = sp.linalg.solve_lyapunov(F, -np.dot(L,np.dot( Qc[0,0],L.T)))
AttributeError: module 'scipy.linalg' has no attribute 'solve_lyapunov'
```

Where solve_lyapunov is called completely independently of your DSYR code as far as I can see and hence the fact that your PR resulted in failing tests is nothing todo with the code you changed - it simply caused a new build to be run; sometime between the last build and now anacondas (installed as miniconda in travis) default packages have likely changed to install scipy 1.0.

We should modify travis to build nightly if we can to try and avoid these issues, and ideally test with a few different versions of our required packages (at least minimum and bleeding edge requirements).

When I first set up the travis script the repo was being updated on a daily basis so this sort of stuff wasn't missed as easily. I'll look into setting up nightly builds and perhaps different requirements when I meet @mzwiessele tomorrow.

I'll make a separate PR to fix the sde kern lyapunov issue as it is a separate fix from your DSYR fix.

Unless anyone thinks I'm missing something?

**Pull request merged**
