### PR TITLE
Binomial laplace #352

### PR DESCRIPTION
**Pull request by alansaul**
Added derivative for Binomial, corrected some maths, and added test. As requested by #352

### CODE REVIEW

**Comment by djsutherland** [comment]
Thanks! I tried actually running my stupid example from the previous notebook [here](https://gist.github.com/9ab8a75177c47f12e6625c5a1f2661b3):
- Basic modeling seemed fine.
- When I tried to optimize the model, the lengthscale went really small and it blew up, but this is probably a Laplace issue and not a code issue....
- `_raw_predict` works.
-  `predict` doen't: it crashes inside the quadrature in `predictive_mean`, because [this line](https://github.com/SheffieldML/GPy/blob/378ac0ad06919d10f2805b8546737596722ea3ac/GPy/likelihoods/likelihood.py#L303) calls `self.conditional_mean(f)` without passing `Y_metadata`. It seems like probably every likelihood needs to be changed to take an optional `Y_metadata` argument, and this line (and presumably similar ones) changed to pass those through.

**Comment by mzwiessele** [comment]
Could you merge in the current devel branch, to see if that is the missing coverage here? Otherwise it looks very good : )

**Comment by djsutherland** [comment]
So, I made the changes I suggested above to the API of `conditional_mean` (in https://github.com/dougalsutherland/GPy/commit/7c3ade9fc5bcf5d22bdfaa8990ed52cb103ffd88), but then noticed that https://github.com/SheffieldML/GPy/commit/ff9ab62db2057a54c2634d308eef21c82e13ffd8 (not included in your branch here, since it was merged to devel just the other day) removed the `BinomialLikelihood.conditional_mean` function entirely, which seems to make `predict` use sampling rather than quadrature. Is there a reason for this, or another way I should be making predictions with a model like this? (@jameshensman?)

**Comment by mzwiessele** [comment]
Great stuff!! when we have fixed the coverage we can start merging 👍

**Comment by mzwiessele** [comment]
Any news on this?

**Comment by djsutherland** [comment]
Bump. I'd really like to distribute some analysis that uses binomial likelihoods, but would also much prefer to just have a requirement on GPy than tell people they need to check out a branch several versions behind the current one....

**Pull request merged**
