### PR TITLE
GPy 1.8.x

### PR DESCRIPTION
**Pull request by mzwiessele**
Newest version of GPy, see CHANGELOG for changes.

### CODE REVIEW

**Comment by alansaul** [comment]
Hey Max, can you hold back from deploying this for this week? We are doing GPSS and don't want to have any surprises in the lab sessions if anything breaks! Cheers

**Comment by mzwiessele** [comment]
Are we good on merging now?

**Comment by zhenwendai** [comment]
Max, I think we have our recent pull requests merged in. Are we ready to release?

**Comment by mzwiessele** [comment]
Yes sure, as long as the tests run through it is as much as a click to accept the merge :)

**Comment by alansaul** [comment]
I'm happy with a release now the summer school is over and most recent pull requests have been merged! Good job everyone.

**Comment by zhenwendai** [comment]
Cool! I think we are ready to move ahead. I don't understand the codecov/changes complaint. 

Max, if you think it is OK, let's release it.

**Comment by mzwiessele** [comment]
Oh no, there is no version update in the pull! It needs a version update, as explained on the main readme of GPy (under deploy).

**Comment by zhenwendai** [comment]
It is my fault. I did not see the instruction about version update. I actually checked the version number and I saw you bumped the version up already. What shall we do now?

**Comment by mzwiessele** [comment]
Oh, never mind then :) the automatic deploy relies on the version number and as the version is 1.8.0 it should all be fine. Did we get any errors from the appveyor or travis ci on the deploy branch?

**Pull request merged**
