### PR TITLE
add offline plotting for plotly

### PR DESCRIPTION
**Pull request by alexfeld**
To address #404

### CODE REVIEW

**Comment by alexfeld** [comment]
I should note that there are other ways to implement this such as importing `offline` or `plotly` at the instantiation of the class itself, but I think this is the most clear way with how you've constructed the `plotting` module thus far.

**Comment by mzwiessele** [comment]
Looks good, did you test it? Unfortunately I don't have access to offline plotting with plotly.

**Comment by alexfeld** [comment]
I tested it using your GP regression example script and it worked as intended with the `plotly.offline.plot` bugs that I mentioned. I've made a request to them to fix the errors. It looks like they can be fixed by only passing `numpy` arrays of the shape `(n,)`, but hopefully they fix this on their end.

**Comment by mzwiessele** [comment]
We should try and make it a backend option, what do you think? We could add a third option "plotly_offline", so we do not need a global parameter. This would then call the library with the offline option.

**Comment by alexfeld** [comment]
I've pushed a commit to address this. There are now three classes in the `plotly_dep.plot_definitions` module. There is a `PlotlyPlotsBase`, `PlotlyPlotsOnline`, and `PlotlyPlotsOffline`. The base class is identical to the old `PlotlyPlots` class but with the `show_canvas` function set to require implementation by a child class. This method is the only thing implemented by the `Offline` and `Online` classes and calls the respective `plot` and `iplot` functions from the `plotly` package.

Allowed inputs to the `GPy.plotting.change_plotting_library` function are `plotly` (preserves old functionality), `plotly_online`, and `plotly_offline`. I tested with the regression example and it worked as expected.

**Comment by mzwiessele** [comment]
That looks awsome! I am on the problems with the new numpy (that's why the builds fail) and will merge them in here before pulling. Great work!

**Comment by alexfeld** [comment]
No problem. Thanks for the great package!

**Comment by mzwiessele** [comment]
Oh wait I just tried it and it actually works! I didn't know you could use plotly offline... Great stuff, holy moly.

**Comment by mzwiessele** [comment]
I added a little workaround with squeeze into the plotting defs over at #482.
As soon as the PR checks it will be pulled and I will update GPy on pip.

Thanks again!

**Comment by alexfeld** [comment]
Ok, sounds good! The offline plotting option is nice but as I mentioned it has some bugs. These are 100% plotly's problem though since if you export the offline plots to plotly's servers they work fine. Hopefully your squeeze fix helps.

**Pull request merged**
