### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by mzwiessele**
Creating 0.8 release through pull request

### CODE REVIEW

**Comment by lawrennd** [comment]
Wow what a list of changes great job *everyone*. Thanks so much to all, but
particularly Max and Mike for leading the process. Also James for chasing
down so many of the outstanding issues.

As from 0.8 we will begin making more regular minor releases. We will form
a developers' meeting, I suspect monthly initially. Then perhaps minor
releases to GPy bimonthly.

Watch this space for more details, they will be hammered out when Mike and
Max have time to catch breath. We'll get in touch directly with some of the
more high volume commiters with details.

Neil

**Comment by mikecroucher** [comment]
Hi all

Great work indeed but I can't take much of the credit.
Max and James did most of the leading - I just took care of a few things
around the edges.

It's been fun!
I think that GPy is something that the whole group should be proud of.

Cheers,
Mike

**Comment by jameshensman** [comment]
Thanks Mike.

One of the things that has changed so much recently in GPy is the nature of
the commits and the committers. Mike and David Menendez have worked on
aspects of GPy that would have been much more difficult for the rest of us
to do. Amongst other things, Mike has used his expertise in Python3 to
implement future compatibility, and David has used his expertise in cython
to significantly ease installation.

GPy has grown to be an important open source project. Browsing the accepted
NIPS papers today I found a paper about GP random fields, with a github
repo and code that depends on GPy. https://github.com/davmre/gprf. I know
that there are several people in the Cambridge and Oxford labs using GPy,
and I intend to make it commonplace in the Lancaster lab too. We have
hundreds of users on the user mailing list. Hundreds of stars on github.

GPy really benefits from this exposure: I know we're always thrilled to
accept pull requests. To reflect the open nature of GPy, I've created a GPy
organisation on github, to which I have invited you all. The intention, as
discussed with many of you, is to move GPy to github.com/gpy/GPy: easily
done with github's transfer feature. The aim of this small change is to
encourage contributions from outside. I for one would be hesitant to
contribute to ManchesterML/foo. There are 78 forks of GPy on github, I hope
we can encourage some of them to contribute back.

With GPy receiving so much exposure, we cannot continue to develop it in
the current fashion. We can't keep telling people "oh, you're not using the
devel branch". Neil has mentioned a more frequent release schedule: to
support this, all development will be done via pull requests. Max and Mike
have begun to work this way already. This is a much more open way to work,
and lots of open projects already work like this (STAN, for example.
Theano. Scikits-learn). It will let us leverage the test suite that we have
all worked so hard to build (PRs should not be accepted without passing
tests!). We will have more clarity and accountability.

One thing that GPy will not be in the future is a place to develop new
ideas. There are now several examples of how to develop alongside GPy. A
shining example is GPyOpt, by Javier. Another is my GPclust project. In
both cases, the projects have benefitted from a stable GPy, but have not
been constrained to the same development rigour that is required of such a
large project. Of course, as holes in GPy are discovered during the
development of these projects, GPy is fixed and patched. And down the line,
as ideas are accepted and published, they can be incorporated into GPy: see
the SVGP code for example. Some projects with different aims might remain
separate (GPclust).

Another reason to change the home and development model of GPy is
maintainability. As people come and go from the lab, we need to ensure that
code shipped with GPy is working and usable. I want to be able to come back
to my code in a year and know that it will still work. There are issues
highlighted on github where code has been moved, removed or broken. With a
new development model, this should't happen.

I have already discussed these ideas with some of you individually. I hope
this is only a continuation of the discussion.

Best wishes,

James.

**Comment by lawrennd** [comment]
Hi James,

I agree with much of what you say, and what you describe is the development
model we have always envisaged. But as I told you quite firmly when you
raised this with me, we will be developing GPy via the SheffieldML repo for
the forseeable future.

Neil

**Comment by Dapid** [comment]
Congratulations on the release! I am glad I could help.

If you are planing on a more frequent release schedule, I think you should consider pushing the new stuff to master, instead to devel; so it is much easier to keep track of the progress, and avoid this huge merges. Releases create their own branch, and maintenance bugfixes are pushed to that branch. This is the model that most open source projects in scientific Python follow.

**Comment by lawrennd** [comment]
That's a really good tip, thanks David!

**Comment by Dapid** [comment]
Github is rolling out a new feature that would make possible not to be allowed to merge PR without all tests passing:

https://github.com/blog/2051-protected-branches-and-required-status-checks

Maybe you could try it out on master, when it is available.

**Comment by lawrennd** [comment]
That would make a lot of sense. My instinct is that after this release GPy
will be stable enough in terms of its feature set for this to be workable.
Plan is to wait for dust to settle while we deliver summer schools over
next two weeks. Then start formulating the new way to perform releases. We
need to increase test coverage and then we can perform pull requests
quicker and with more confidence.

Thanks for drawing this to our attention David.

**Pull request merged**
