### PR TITLE
Fix the issue of negative predicted variance of normal GP

### PR DESCRIPTION
**Pull request by zhenwendai**
1. Fix the issue of negative predicted variance of normal GP
2. get rid of mpi4py when import
3. fix gpu initialization

### CODE REVIEW

**Comment by mzwiessele** [comment]
@zhenwendai could you add tests to run the code, so that the coverage is provided for these changes?

**Comment by zhenwendai** [comment]
Sure. One of the changes is only an interface. There is no real runnable 
code in GPy. I will do for the rest.

Zhenwen

**Comment by mzwiessele** [comment]
Do we have an update on this?

**Comment by mzwiessele** [comment]
I recently tried to run the SSGPLVM example and it seemed to fail sporadically. Can we get some tests, testing the gradients and run the code inside the tests, so that we can have this good work for the future and versions to come?

**Comment by zhenwendai** [comment]
I can add test cases for gradient checks. One problem of spike and slab 
model is that it depends a lot on initialization. With random 
initialization, it might fail randomly.

Zhenwen

**Comment by mzwiessele** [comment]
Great, gradient checks are fine to work with, at least the code gets run then. Try to check branching code, like if statements thoroughly, so that we dont get surprised by changes. You might want to have a look at the mnibatch_tests.py. 

There is a great package called coverage to check coverage locally. When installed you can run from the root directory:

coverage run travis_tests.py
coverage html

and it will create a coverage report for you. You can see the coverage of all files then in htmlcov directory. This also shows the branching coverage and unhandled special cases.

**Comment by mzwiessele** [comment]
Updates? Is this the new pull request, or still the old one?

**Comment by zhenwendai** [comment]
@mzwiessele 
Sorry for the slowness. 
1.  I have added a testcase for SSGPLVM.
2.  The metropolis hastings code is new and compatible with the param framework (I didn't know before). I did a bug fix. It can run now, but I didn't check the correctness of the results. I added a testcase that makes sure it is runnable.

fixes #253
fixes #154

**Comment by mzwiessele** [comment]
Thanks so much! There is copied code now between sparse gp and normal gp predict functions. is that necessary? Can we not get those together into one, so that when we make changes they are reflected in both sparse gp and gp?

**Comment by zhenwendai** [comment]
It is different from the default sparse gp prediction, because the 
solution of the numerical problem is to solve the covariance matrix in 
the fly. Unfortunately, the prediction code can only be shared between 
normal gp, sparse gp and Bayesian GPLVM if we store the inversion of 
woodburry matrix (the numerical instable way). Therefore, I implement 
the _raw_predict function in the posterior object, so that different 
model can have different numerical stable implementation.

Zhenwen

**Comment by mzwiessele** [comment]
Ahh nice, I like it! So we can get rid of the prediction code in GP and SparseGP and put it in the super class of Posterior?

**Comment by zhenwendai** [comment]
Cool! I have done the modification correspondingly. I have moved the _raw_predict function into posterior object. 

The modification of the testcase is to allow the behavior of clipping the negative predicted variance.

**Pull request merged**
