### PR TITLE
updateXY problem in EP module using GPClassification

### PR DESCRIPTION
**Pull request by ric70x7**
I think this solves the bug.

### CODE REVIEW

**Comment by mzwiessele** [comment]
Hi Ricardo,

Did you forget to update the imports? On the travis tests it fails on an 
import...

Max Zwiessele
Sheffield Institute of Translational Neuroscience
University of Sheffield
385a Glossop Road,
S10 2HQ, Sheffield,
United Kingdom

eMail: ibinbei@gmail.com
Website: http://staffwww.dcs.sheffield.ac.uk/people/M.Zwiessele/

**Comment by ric70x7** [comment]
Yes,  sorry. I forgot to do that. I'll have a look at it.
Cheers
Ricardo

**Comment by mzwiessele** [comment]
Have we got an update on this? This is a pull request for master, could you change it to devel and resubmit new pull request?

**Comment by ric70x7** [comment]
Ok, I've closed the pull request and branched from devel.
Cheers,
Ricardo

2016-03-08 8:29 GMT-08:00 Max Zwiessele notifications@github.com:

**Pull request closed without merging**
